server:
  port: 8080
mybatis:
  mapper-locations: classpath:/com/suixingpay/mapper/*.xml
  type-aliases-package: com.suixingpay.pojo
spring:
  profiles:
    active: dev
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/patent?setUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1933333333