server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.suixingpay.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

  profiles:
    active: dev
  datasource:
    platform: mysql
    url: jdbc:mysql://172.16.41.67:3306/patent_zwl?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: team3member
    password: team3team3
